# Generated by Django 2.1.1 on 2018-09-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20180922_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banknote',
            name='denominator',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='banknote',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
